"""add append-only investigation intelligence records
Revision ID: 0011
Revises: 0010
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="0011"; down_revision="0010"; branch_labels=None; depends_on=None
def upgrade():
 u=postgresql.UUID(as_uuid=True)
 op.create_table("intelligence_analyses",sa.Column("id",u,primary_key=True),sa.Column("org_id",u,nullable=False),sa.Column("investigation_id",u,nullable=False),sa.Column("provider",sa.String(64),nullable=False),sa.Column("model",sa.String(255),nullable=False),sa.Column("prompt_template_version",sa.String(64),nullable=False),sa.Column("input_snapshot",postgresql.JSONB(),nullable=False),sa.Column("input_hash",sa.String(64),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("generated_at",sa.DateTime(timezone=True)),sa.Column("error_summary",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.ForeignKeyConstraint(["investigation_id"],["investigations.id"],ondelete="RESTRICT"),sa.CheckConstraint("status IN ('RUNNING','COMPLETED','FAILED')",name="ck_intelligence_analyses_status"));op.create_index("ix_intelligence_analyses_org_id","intelligence_analyses",["org_id"]);op.create_index("ix_intelligence_analyses_investigation_generated","intelligence_analyses",["investigation_id","generated_at"])
 op.create_table("intelligence_items",sa.Column("id",u,primary_key=True),sa.Column("org_id",u,nullable=False),sa.Column("analysis_id",u,nullable=False),sa.Column("investigation_id",u,nullable=False),sa.Column("kind",sa.String(20),nullable=False),sa.Column("ordinal",sa.Integer(),nullable=False),sa.Column("statement",sa.Text(),nullable=False),sa.Column("confidence",sa.Integer()),sa.Column("payload",postgresql.JSONB(),nullable=False),sa.Column("review_status",sa.String(20),nullable=False,server_default="UNREVIEWED"),sa.Column("reviewed_by_id",u),sa.Column("reviewed_at",sa.DateTime(timezone=True)),sa.Column("review_rationale",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.ForeignKeyConstraint(["analysis_id"],["intelligence_analyses.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["investigation_id"],["investigations.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["reviewed_by_id"],["users.id"],ondelete="RESTRICT"),sa.CheckConstraint("kind IN ('SUMMARY','OBSERVATION','HYPOTHESIS','RECOMMENDATION','QUESTION','REASONING')",name="ck_intelligence_items_kind"),sa.CheckConstraint("review_status IN ('UNREVIEWED','APPROVED','REJECTED','SUPERSEDED')",name="ck_intelligence_items_review"));op.create_index("ix_intelligence_items_org_id","intelligence_items",["org_id"]);op.create_index("ix_intelligence_items_analysis_kind","intelligence_items",["analysis_id","kind"])
 op.create_table("intelligence_fact_links",sa.Column("id",u,primary_key=True),sa.Column("org_id",u,nullable=False),sa.Column("item_id",u,nullable=False),sa.Column("fact_type",sa.String(64),nullable=False),sa.Column("fact_id",u,nullable=False),sa.Column("role",sa.String(20),nullable=False),sa.ForeignKeyConstraint(["item_id"],["intelligence_items.id"],ondelete="RESTRICT"),sa.CheckConstraint("role IN ('SUPPORTS','CONTRADICTS','CONTEXT')",name="ck_intelligence_fact_links_role"));op.create_index("ix_intelligence_fact_links_org_id","intelligence_fact_links",["org_id"]);op.create_index("ix_intelligence_fact_links_item","intelligence_fact_links",["item_id"])
def downgrade(): op.drop_table("intelligence_fact_links");op.drop_table("intelligence_items");op.drop_table("intelligence_analyses")
