"""add analyst findings and reviewable MITRE mappings
Revision ID: 0013
Revises: 0012
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="0013"; down_revision="0012"; branch_labels=None; depends_on=None
def upgrade():
 u=postgresql.UUID(as_uuid=True)
 op.create_table("findings",sa.Column("id",u,primary_key=True),sa.Column("org_id",u,nullable=False),sa.Column("investigation_id",u,nullable=False),sa.Column("source_intelligence_item_id",u),sa.Column("source_analysis_id",u),sa.Column("title",sa.String(255),nullable=False),sa.Column("description",sa.Text(),nullable=False),sa.Column("severity",sa.String(20),nullable=False),sa.Column("confidence",sa.Integer()),sa.Column("status",sa.String(20),nullable=False),sa.Column("analyst_id",u,nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.ForeignKeyConstraint(["investigation_id"],["investigations.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["source_intelligence_item_id"],["intelligence_items.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["source_analysis_id"],["intelligence_analyses.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["analyst_id"],["users.id"],ondelete="RESTRICT"),sa.UniqueConstraint("source_intelligence_item_id",name="uq_findings_source_item"));op.create_index("ix_findings_org_id","findings",["org_id"]);op.create_index("ix_findings_investigation_id","findings",["investigation_id"])
 for table,parent in (("finding_fact_links","findings"),("mitre_mapping_fact_links","mitre_mappings")):
  if table=="finding_fact_links": op.create_table(table,sa.Column("id",u,primary_key=True),sa.Column("org_id",u,nullable=False),sa.Column("finding_id",u,nullable=False),sa.Column("fact_type",sa.String(64),nullable=False),sa.Column("fact_id",u,nullable=False),sa.Column("role",sa.String(20),nullable=False),sa.ForeignKeyConstraint(["finding_id"],["findings.id"],ondelete="RESTRICT"));op.create_index("ix_finding_fact_links_org_id",table,["org_id"]);op.create_index("ix_finding_fact_links_finding_id",table,["finding_id"])
 op.create_table("mitre_mappings",sa.Column("id",u,primary_key=True),sa.Column("org_id",u,nullable=False),sa.Column("investigation_id",u,nullable=False),sa.Column("source_intelligence_item_id",u),sa.Column("finding_id",u),sa.Column("technique_id",sa.String(32),nullable=False),sa.Column("technique_name",sa.String(255)),sa.Column("tactic",sa.String(100)),sa.Column("confidence",sa.Integer()),sa.Column("ai_rationale",sa.Text(),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("reviewed_by_id",u),sa.Column("reviewed_at",sa.DateTime(timezone=True)),sa.Column("review_rationale",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.ForeignKeyConstraint(["investigation_id"],["investigations.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["source_intelligence_item_id"],["intelligence_items.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["finding_id"],["findings.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["reviewed_by_id"],["users.id"],ondelete="RESTRICT"));op.create_index("ix_mitre_mappings_org_id","mitre_mappings",["org_id"]);op.create_index("ix_mitre_mappings_investigation_id","mitre_mappings",["investigation_id"])
 op.create_table("mitre_mapping_fact_links",sa.Column("id",u,primary_key=True),sa.Column("org_id",u,nullable=False),sa.Column("mapping_id",u,nullable=False),sa.Column("fact_type",sa.String(64),nullable=False),sa.Column("fact_id",u,nullable=False),sa.Column("role",sa.String(20),nullable=False),sa.ForeignKeyConstraint(["mapping_id"],["mitre_mappings.id"],ondelete="RESTRICT"));op.create_index("ix_mitre_mapping_fact_links_org_id","mitre_mapping_fact_links",["org_id"]);op.create_index("ix_mitre_mapping_fact_links_mapping_id","mitre_mapping_fact_links",["mapping_id"])
def downgrade():
 op.drop_table("mitre_mapping_fact_links");op.drop_table("mitre_mappings");op.drop_table("finding_fact_links");op.drop_table("findings")
