import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import type { ReactNode } from "react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { NotesWorkspace } from "@/components/investigations/notes-workspace";
const state=vi.hoisted(()=>({api:vi.fn(),perms:["investigation:read","investigation:write"] as string[]}));
vi.mock("next/link",()=>({default:({href,children}:{href:string;children:ReactNode})=><a href={href}>{children}</a>}));
vi.mock("@/lib/auth-context",()=>({useAuth:()=>({hasPermission:(p:string)=>state.perms.includes(p)})}));
vi.mock("@/lib/api-client",()=>({apiFetch:state.api,ApiError:class ApiError extends Error {constructor(message:string,public status:number){super(message)}}}));
type Note = { id: string; author_id: string; body: string; created_at: string; updated_at: string };
const page=(items: Note[]=[] ,offset=0,total=items.length)=>({items,offset,total,limit:25}); const note: Note={id:"n1",author_id:"author",body:"<img src=x onerror=alert(1)>\ntext",created_at:"2026-01-01T00:00:00Z",updated_at:"2026-01-01T00:00:00Z"};
afterEach(cleanup);beforeEach(()=>{state.api.mockReset();state.perms=["investigation:read","investigation:write"];});
describe("NotesWorkspace",()=>{
 it("renders server notes inertly and creates then refreshes",async()=>{state.api.mockResolvedValueOnce(page([note])).mockResolvedValueOnce({}).mockResolvedValueOnce(page([note]));render(<NotesWorkspace id="case 1"/>);expect(await screen.findByText(/<img src=x/)).toBeVisible();expect(document.querySelector("img")).toBeNull();const area=screen.getByLabelText("Add note");fireEvent.change(area,{target:{value:"new note"}});fireEvent.click(screen.getByRole("button",{name:"Save note"}));await waitFor(()=>expect(state.api).toHaveBeenCalledWith("/api/v1/investigations/case%201/notes",expect.objectContaining({method:"POST"})));expect((area as HTMLTextAreaElement).value).toBe("");});
 it("shows empty, read-only, validation and pagination controls",async()=>{state.api.mockResolvedValue(page());render(<NotesWorkspace id="case"/>);expect(await screen.findByRole("heading",{name:"No notes"})).toBeVisible();state.perms=["investigation:read"];cleanup();state.api.mockResolvedValue(page([note],0,26));render(<NotesWorkspace id="case"/>);expect(await screen.findByText("Author:")).toBeVisible();expect(screen.queryByLabelText("Add note")).toBeNull();expect(screen.getByRole("button",{name:"Next"})).toBeEnabled();});
 it("handles 403, 404, retry and abort",async()=>{const {ApiError}=await import("@/lib/api-client");state.api.mockRejectedValueOnce(new ApiError("x",403));render(<NotesWorkspace id="a"/>);expect(await screen.findByRole("heading",{name:"Permission denied"})).toBeVisible();cleanup();state.api.mockRejectedValueOnce(new ApiError("x",404));render(<NotesWorkspace id="a"/>);expect(await screen.findByRole("heading",{name:"Not found"})).toBeVisible();});
 it("uses server pagination and retries bounded failures",async()=>{state.api.mockResolvedValueOnce(page([note],0,26)).mockResolvedValueOnce(page([note],25,26));render(<NotesWorkspace id="case"/>);await screen.findByText(/Showing 1–1/);fireEvent.click(screen.getByRole("button",{name:"Next"}));await waitFor(()=>expect(state.api).toHaveBeenLastCalledWith(expect.stringContaining("offset=25"),expect.anything()));cleanup();state.api.mockRejectedValueOnce(new Error("network")).mockResolvedValueOnce(page());render(<NotesWorkspace id="case"/>);expect(await screen.findByRole("heading",{name:"Unable to load notes"})).toBeVisible();fireEvent.click(screen.getByRole("button",{name:"Retry"}));expect(await screen.findByRole("heading",{name:"No notes"})).toBeVisible();});
 it("aborts in-flight notes reads when unmounted",async()=>{let signal: AbortSignal | undefined;state.api.mockImplementation((_path: string, options?: {signal?: AbortSignal})=>{signal=options?.signal;return new Promise(()=>{});});const view=render(<NotesWorkspace id="case"/>);await waitFor(()=>expect(signal).toBeDefined());view.unmount();expect(signal?.aborted).toBe(true);});
});
