"use client";

import { ChangeEvent, useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { apiFetch, ApiError, downloadFile } from "@/lib/api-client";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { WorkspaceNav } from "./workspace-nav";

type Evidence = { id: string; original_filename: string; sha256: string; byte_size: number; detected_mime: string; source_description: string; imported_at: string; parsing_status: string; parser_name: string | null; parser_version: string | null };
type Raw = { id: string; ordinal: number; content: string | null; content_type: string; byte_offset: number | null; line_start: number | null; line_end: number | null };
type Event = { id: string; evidence_id: string; raw_record_id: string; timestamp: string | null; host: string | null; user: string | null; source_ip: string | null; destination_ip: string | null; event_type: string | null; normalized: Record<string, unknown> };
type Indicator = { id: string; type: string; normalized_value: string; occurrence_count: number; first_seen_at: string | null; last_seen_at: string | null };
type Entity = { id: string; type: string; canonical_value: string; display_name: string; first_seen_at: string | null; last_seen_at: string | null };
type Relationship = { id: string; source_entity_id: string; target_entity_id: string; relationship_type: string; evidence_id: string | null; raw_record_id: string | null; event_id: string | null; observed_at: string | null };
type Observation = { evidence_id: string; event_id: string | null; raw_record_id: string; observed_at: string | null };

const fmt = (value: string | null | undefined) => value ? new Date(value).toLocaleString() : "—";

function Shell({ id, title, children }: { id: string; title: string; children: React.ReactNode }) {
  return <><div className="mb-2 text-xs text-text-muted"><Link href="/investigations">Cases</Link> / Investigation workspace</div><h1 className="font-display text-lg text-text-primary">{title}</h1><WorkspaceNav investigationId={id} />{children}</>;
}

function State({ loading, error, empty, children }: { loading: boolean; error: string | null; empty?: boolean; children: React.ReactNode }) {
  if (loading) return <div className="text-sm text-text-muted">Loading factual data…</div>;
  if (error) return <div className="rounded border border-severity-critical/40 p-3 text-sm text-severity-critical">{error}</div>;
  if (empty) return <div className="rounded border border-hairline p-4 text-sm text-text-muted">No canonical factual data yet.</div>;
  return <>{children}</>;
}

function Provenance({ item, investigationId }: { item: Observation; investigationId: string }) {
  return <div className="mt-2 rounded border border-hairline p-2 text-xs">Evidence <Link className="text-signal" href={`/investigations/${investigationId}/evidence`}>{item.evidence_id}</Link><br />Event: {item.event_id || "not normalized"}<br />Raw record: {item.raw_record_id}<br />Observed: {fmt(item.observed_at)}</div>;
}

export function EvidenceWorkspace({ id }: { id: string }) {
  const [rows, setRows] = useState<Evidence[]>([]); const [selected, setSelected] = useState<Evidence | null>(null); const [raw, setRaw] = useState<Raw[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [uploading, setUploading] = useState(false);
  const load = useCallback(async () => { try { setLoading(true); setRows(await apiFetch<Evidence[]>(`/api/v1/investigations/${id}/evidence`)); } catch (err) { setError(err instanceof ApiError ? err.message : "Unable to load evidence."); } finally { setLoading(false); } }, [id]);
  useEffect(() => { load(); }, [load]);
  async function choose(evidence: Evidence) { setSelected(evidence); try { setRaw(await apiFetch<Raw[]>(`/api/v1/investigations/${id}/evidence/${evidence.id}/raw-records`)); } catch (err) { setError(err instanceof ApiError ? err.message : "Unable to load raw records."); } }
  async function upload(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; setUploading(true); setError(null); try { const form = new FormData(); form.append("file", file); await apiFetch<Evidence>(`/api/v1/investigations/${id}/evidence`, { method: "POST", body: form }); await load(); } catch (err) { setError(err instanceof ApiError ? err.message : "Evidence upload failed."); } finally { setUploading(false); event.target.value = ""; } }
  return <Shell id={id} title="Evidence"><State loading={loading} error={error} empty={!rows.length}><div className="grid gap-4 lg:grid-cols-[1fr_360px]"><Card><div className="mb-3 flex justify-between"><b className="text-sm">Evidence inventory</b><label className="cursor-pointer text-xs text-signal">{uploading ? "Uploading…" : "Upload evidence"}<input className="hidden" type="file" accept=".log,.txt,.json,.csv" disabled={uploading} onChange={upload} /></label></div><table className="w-full text-left text-xs"><thead className="text-text-muted"><tr><th>Filename / source</th><th>Type / parser</th><th>Status</th><th>SHA-256</th><th>Imported</th></tr></thead><tbody>{rows.map(row => <tr key={row.id} onClick={() => choose(row)} className="cursor-pointer border-t border-hairline hover:bg-surface-raised"><td className="py-2">{row.original_filename}<br /><span className="text-text-muted">{row.source_description || "No description"}</span></td><td>{row.detected_mime} · {row.byte_size} bytes<br /><span className="text-text-muted">{row.parser_name || "No parser"}{row.parser_version ? ` ${row.parser_version}` : ""}</span></td><td>{row.parsing_status}</td><td className="font-mono">{row.sha256.slice(0, 16)}…</td><td>{fmt(row.imported_at)}</td></tr>)}</tbody></table></Card><Card>{selected ? <><b className="text-sm">Evidence inspector</b><dl className="mt-3 space-y-2 text-xs"><div><dt className="text-text-muted">Type / size</dt><dd>{selected.detected_mime} · {selected.byte_size} bytes</dd></div><div><dt className="text-text-muted">Parser</dt><dd>{selected.parser_name || "Not available"}{selected.parser_version ? ` ${selected.parser_version}` : ""}</dd></div><div><dt className="text-text-muted">SHA-256</dt><dd className="break-all font-mono">{selected.sha256}</dd></div><Button variant="secondary" className="mt-2" onClick={() => downloadFile(`/api/v1/investigations/${id}/evidence/${selected.id}/download`)}>Download safely</Button></dl>{selected.parsing_status === "failed" && <p className="mt-3 rounded border border-severity-critical/40 p-2 text-xs text-severity-critical">Parsing failed. The original evidence remains preserved.</p>}<div className="mt-4 border-t border-hairline pt-3 text-xs"><b>Raw records</b>{raw.map(record => <details key={record.id} className="mt-2 rounded border border-hairline p-2"><summary>#{record.ordinal} · {record.content_type}</summary><pre className="mt-2 whitespace-pre-wrap text-[11px] text-text-muted">{record.content}</pre></details>)}</div></> : <span className="text-sm text-text-muted">Select evidence to inspect provenance.</span>}</Card></div></State></Shell>;
}

export function TimelineWorkspace({ id }: { id: string }) {
  const [events, setEvents] = useState<Event[]>([]); const [evidence, setEvidence] = useState<Evidence[]>([]); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [selected, setSelected] = useState<Event | null>(null); const [filters, setFilters] = useState({ host: "", user: "", sourceIp: "", destinationIp: "", eventType: "", evidence: "", from: "", to: "" });
  useEffect(() => { Promise.all([apiFetch<Event[]>(`/api/v1/investigations/${id}/events`), apiFetch<Evidence[]>(`/api/v1/investigations/${id}/evidence`)]).then(([eventRows, evidenceRows]) => { setEvents(eventRows); setEvidence(evidenceRows); }).catch(err => setError(err instanceof ApiError ? err.message : "Unable to load timeline.")).finally(() => setLoading(false)); }, [id]);
  const shown = useMemo(() => events.filter(event => (!filters.host || event.host === filters.host) && (!filters.user || event.user === filters.user) && (!filters.sourceIp || event.source_ip === filters.sourceIp) && (!filters.destinationIp || event.destination_ip === filters.destinationIp) && (!filters.eventType || event.event_type === filters.eventType) && (!filters.evidence || event.evidence_id === filters.evidence) && (!filters.from || !event.timestamp || event.timestamp >= filters.from) && (!filters.to || !event.timestamp || event.timestamp <= filters.to)), [events, filters]);
  const set = (key: keyof typeof filters, value: string) => setFilters(previous => ({ ...previous, [key]: value }));
  return <Shell id={id} title="Canonical timeline"><State loading={loading} error={error} empty={!events.length}><Card><div className="sticky top-0 mb-3 flex flex-wrap gap-2 bg-surface"><input type="datetime-local" aria-label="Start time" onChange={event => set("from", event.target.value)} /><input type="datetime-local" aria-label="End time" onChange={event => set("to", event.target.value)} /><input placeholder="Host" onChange={event => set("host", event.target.value)} /><input placeholder="User" onChange={event => set("user", event.target.value)} /><input placeholder="Source IP" onChange={event => set("sourceIp", event.target.value)} /><input placeholder="Destination IP" onChange={event => set("destinationIp", event.target.value)} /><input placeholder="Event type" onChange={event => set("eventType", event.target.value)} /><select onChange={event => set("evidence", event.target.value)}><option value="">All evidence</option>{evidence.map(item => <option value={item.id} key={item.id}>{item.original_filename}</option>)}</select></div><div className="grid gap-3 lg:grid-cols-[1fr_320px]"><table className="text-left text-xs"><thead className="text-text-muted"><tr><th>Time</th><th>Type</th><th>Host</th><th>User</th><th>Network</th></tr></thead><tbody>{shown.map(event => <tr onClick={() => setSelected(event)} className="cursor-pointer border-t border-hairline hover:bg-surface-raised" key={event.id}><td className="py-2">{fmt(event.timestamp)}</td><td>{event.event_type}</td><td>{event.host}</td><td>{event.user}</td><td>{event.source_ip} → {event.destination_ip}</td></tr>)}</tbody></table><aside className="border-l border-hairline pl-3 text-xs">{selected ? <><b>Event provenance</b><pre className="mt-3 max-h-72 overflow-auto whitespace-pre-wrap text-text-muted">{JSON.stringify(selected.normalized, null, 2)}</pre><p className="mt-3">Evidence: <Link className="text-signal" href={`/investigations/${id}/evidence`}>{evidence.find(item => item.id === selected.evidence_id)?.original_filename || selected.evidence_id}</Link></p><p>Raw record: <code>{selected.raw_record_id}</code></p></> : "Select an event to inspect normalized fields and source provenance."}</aside></div></Card></State></Shell>;
}

export function IndicatorsWorkspace({ id }: { id: string }) {
  const [rows, setRows] = useState<Indicator[]>([]); const [selected, setSelected] = useState<Indicator | null>(null); const [occurrences, setOccurrences] = useState<Observation[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  useEffect(() => { apiFetch<Indicator[]>(`/api/v1/investigations/${id}/indicators`).then(setRows).catch(err => setError(err instanceof ApiError ? err.message : "Unable to load indicators.")).finally(() => setLoading(false)); }, [id]);
  async function choose(item: Indicator) { setSelected(item); try { setOccurrences(await apiFetch<Observation[]>(`/api/v1/investigations/${id}/indicators/${item.id}/occurrences`)); } catch (err) { setError(err instanceof ApiError ? err.message : "Unable to load indicator provenance."); } }
  return <Shell id={id} title="Canonical indicators"><State loading={loading} error={error} empty={!rows.length}><div className="grid gap-4 lg:grid-cols-[1fr_330px]"><Card><table className="w-full text-left text-xs"><thead className="text-text-muted"><tr><th>Type</th><th>Value</th><th>Occurrences</th><th>First / last seen</th></tr></thead><tbody>{rows.map(row => <tr key={row.id} onClick={() => choose(row)} className="cursor-pointer border-t border-hairline hover:bg-surface-raised"><td className="py-2 uppercase">{row.type}</td><td className="font-mono">{row.normalized_value}</td><td>{row.occurrence_count}</td><td>{fmt(row.first_seen_at)}<br />{fmt(row.last_seen_at)}</td></tr>)}</tbody></table></Card><Card>{selected ? <><b className="text-sm">Occurrence provenance</b><p className="mt-2 font-mono text-xs">{selected.normalized_value}</p>{occurrences.map((item, index) => <Provenance key={`${item.raw_record_id}-${index}`} item={item} investigationId={id} />)}</> : <span className="text-sm text-text-muted">Select an indicator. No reputation or verdict is assigned here.</span>}</Card></div></State></Shell>;
}

export function EntitiesWorkspace({ id }: { id: string }) {
  const [rows, setRows] = useState<Entity[]>([]); const [selected, setSelected] = useState<Entity | null>(null); const [observations, setObservations] = useState<Observation[]>([]); const [relationships, setRelationships] = useState<Relationship[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  useEffect(() => { Promise.all([apiFetch<Entity[]>(`/api/v1/investigations/${id}/entities`), apiFetch<Relationship[]>(`/api/v1/investigations/${id}/relationships`)]).then(([entityRows, relationshipRows]) => { setRows(entityRows); setRelationships(relationshipRows); }).catch(err => setError(err instanceof ApiError ? err.message : "Unable to load entities.")).finally(() => setLoading(false)); }, [id]);
  async function choose(item: Entity) { setSelected(item); try { setObservations(await apiFetch<Observation[]>(`/api/v1/investigations/${id}/entities/${item.id}/observations`)); } catch (err) { setError(err instanceof ApiError ? err.message : "Unable to load entity provenance."); } }
  return <Shell id={id} title="Canonical entities"><State loading={loading} error={error} empty={!rows.length}><div className="grid gap-4 lg:grid-cols-[1fr_330px]"><Card><table className="w-full text-left text-xs"><thead className="text-text-muted"><tr><th>Type</th><th>Canonical value</th><th>First / last seen</th></tr></thead><tbody>{rows.map(row => <tr key={row.id} onClick={() => choose(row)} className="cursor-pointer border-t border-hairline hover:bg-surface-raised"><td className="py-2 uppercase">{row.type}</td><td>{row.display_name}<br /><span className="font-mono text-text-muted">{row.canonical_value}</span></td><td>{fmt(row.first_seen_at)}<br />{fmt(row.last_seen_at)}</td></tr>)}</tbody></table></Card><Card>{selected ? <><b className="text-sm">Entity provenance</b><p className="mt-2">{selected.display_name}</p><p className="text-xs text-text-muted">Observations: {observations.length}; relationships: {relationships.filter(item => item.source_entity_id === selected.id || item.target_entity_id === selected.id).length}</p>{observations.map((item, index) => <Provenance key={`${item.raw_record_id}-${index}`} item={item} investigationId={id} />)}</> : <span className="text-sm text-text-muted">Select an entity to inspect observations and factual relationships.</span>}</Card></div></State></Shell>;
}

export function OverviewWorkspace({ id }: { id: string }) {
  const [data, setData] = useState<{ evidence: Evidence[]; events: Event[]; indicators: Indicator[]; entities: Entity[]; relationships: Relationship[]; rawCount: number; findings: number; confirmedMitre: number; analysis: string } | null>(null);
  useEffect(() => { Promise.all([apiFetch<Evidence[]>(`/api/v1/investigations/${id}/evidence`), apiFetch<Event[]>(`/api/v1/investigations/${id}/events`), apiFetch<Indicator[]>(`/api/v1/investigations/${id}/indicators`), apiFetch<Entity[]>(`/api/v1/investigations/${id}/entities`), apiFetch<Relationship[]>(`/api/v1/investigations/${id}/relationships`), apiFetch<{ id: string }[]>(`/api/v1/investigations/${id}/findings`).catch(() => []), apiFetch<{ status: string }[]>(`/api/v1/investigations/${id}/mitre-mappings`).catch(() => []), apiFetch<{ status: string }>(`/api/v1/investigations/${id}/intelligence`).catch(() => ({ status: "Not run" }))]).then(async ([evidence, events, indicators, entities, relationships, findings, mitre, intelligence]) => { const raw = await Promise.all(evidence.map(item => apiFetch<Raw[]>(`/api/v1/investigations/${id}/evidence/${item.id}/raw-records`))); setData({ evidence, events, indicators, entities, relationships, rawCount: raw.reduce((count, rows) => count + rows.length, 0), findings: findings.length, confirmedMitre: mitre.filter(row => row.status === "CONFIRMED").length, analysis: intelligence.status }); }); }, [id]);
  return <Shell id={id} title="Investigation overview">{!data ? <div className="text-sm text-text-muted">Loading factual summary…</div> : <><div className="grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-5">{[["Evidence", data.evidence.length], ["Raw records", data.rawCount], ["Events", data.events.length], ["Indicators", data.indicators.length], ["Entities", data.entities.length], ["Relationships", data.relationships.length], ["Findings", data.findings], ["Confirmed MITRE", data.confirmedMitre], ["Latest AIIE", data.analysis]].map(([label, count]) => <Card key={String(label)}><div className="text-xs text-text-muted">{label}</div><div className="mt-1 text-lg">{count}</div></Card>)}</div><Card className="mt-4"><b className="text-sm">Canonical factual metrics</b><p className="mt-2 text-xs text-text-muted">FACT counts are derived from canonical evidence, events, indicators, entities and relationships. Findings and confirmed MITRE are analyst verdicts; AIIE is displayed separately.</p></Card></>}</Shell>;
}

export function PlaceholderWorkspace({ id, title }: { id: string; title: string }) {
  return <Shell id={id} title={title}><Card><p className="text-sm text-text-muted">This workspace section is a compatibility placeholder. Its existing legacy surface remains available until its dedicated migration phase.</p></Card></Shell>;
}
