"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { apiFetch, ApiError } from "@/lib/api-client";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { WorkspaceNav } from "@/components/investigations/workspace-nav";
type Finding={id:string;title:string;description:string;severity:string;confidence:number|null;status:string;source_intelligence_item_id:string|null;fact_links:{fact_id:string;fact_type:string;role:string}[]};
export default function FindingsPage(){const {id}=useParams<{id:string}>();const [items,setItems]=useState<Finding[]|null>(null);const [error,setError]=useState<string|null>(null);const [title,setTitle]=useState("");const [description,setDescription]=useState("");const load=useCallback(async()=>{try{setItems(await apiFetch<Finding[]>(`/api/v1/investigations/${id}/findings`));}catch(e){setError(e instanceof ApiError?e.message:"Unable to load findings.");}},[id]);useEffect(()=>{void load();},[load]);async function create(){try{await apiFetch(`/api/v1/investigations/${id}/findings`,{method:"POST",body:JSON.stringify({title,description,severity:"medium"})});setTitle("");setDescription("");await load();}catch(e){setError(e instanceof ApiError?e.message:"Unable to create finding.");}}async function status(finding:string,status:string){await apiFetch(`/api/v1/investigations/findings/${finding}/status`,{method:"POST",body:JSON.stringify({status})});await load();}return <><h1 className="font-display text-lg">Findings <span className="text-xs font-normal text-cognition">ANALYST VERDICT</span></h1><WorkspaceNav investigationId={id}/><Card className="mb-3"><div className="grid gap-2 md:grid-cols-2"><input aria-label="Finding title" value={title} onChange={e=>setTitle(e.target.value)} placeholder="Finding title" className="rounded border border-hairline bg-surface-raised p-2 text-sm"/><input aria-label="Finding description" value={description} onChange={e=>setDescription(e.target.value)} placeholder="Analyst conclusion" className="rounded border border-hairline bg-surface-raised p-2 text-sm"/></div><Button className="mt-2" disabled={!title||!description} onClick={create}>Create finding</Button></Card>{error?<Card>{error}</Card>:!items?<p className="text-sm text-text-muted">Loading findings…</p>:items.length===0?<Card>No analyst findings yet.</Card>:<div className="space-y-3">{items.map(item=><Card key={item.id}><div className="flex justify-between"><b>{item.title}</b><span className="text-xs text-cognition">{item.status} · {item.severity}</span></div><p className="mt-2 text-sm">{item.description}</p>{item.source_intelligence_item_id&&<p className="mt-2 text-xs text-text-muted">AI INFERENCE: <Link className="text-signal" href={`/investigations/${id}/intelligence`}>{item.source_intelligence_item_id}</Link></p>}<p className="mt-2 text-xs text-text-muted">FACT provenance: {item.fact_links.map(link=><Link className="mr-2 text-signal" key={link.fact_id} href={`/investigations/${id}/evidence`}>{link.role}: {link.fact_id}</Link>)}</p><div className="mt-2 flex gap-2">{["CONFIRMED","DISMISSED","RESOLVED"].map(next=><button key={next} onClick={()=>void status(item.id,next)} className="text-xs text-signal">{next}</button>)}</div></Card>)}</div>}</>}
